name: Build and Deploy Docker on VM

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        # Use GitHub Secret to securely provide the SSH private key
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Optionally, add the VM's public key to known hosts to prevent verification prompt
        ssh-keyscan -H 34.132.171.168 >> ~/.ssh/known_hosts

    - name: SSH into VM and run Docker commands
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@34.132.171.168 << 'EOF'
          # Navigate to the directory where your Dockerfiles are located
          cd /home/kiritisagar
          
          # Build Docker image
          docker build -t your-image-name .
          
          # Run the Docker container
          docker run -d -p 80:80 your-image-name
        EOF
