name: Build and Run Docker Containers on VM

on:
  push:
    branches:
      - main  # Trigger workflow on push to the main branch
  pull_request:
    branches:
      - main  # Trigger workflow on PR creation or update to the main branch

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH key for authentication
    - name: Set up SSH key for VM
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Optionally, add the VM's public key to known hosts to prevent verification prompt
        ssh-keyscan -H 34.132.171.168 >> ~/.ssh/known_hosts

    # Step 3: SSH into VM and run Docker build and container commands
    - name: Connect to VM and Build & Run Docker Containers
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@<your-vm-ip> << 'EOF'
          # Navigate to the directory where your Dockerfiles are located
          cd /home/kiritisagar

          # Build Docker image
          docker build -t your-image-name .

          # Run the Docker container
          docker run -d -p 80:80 your-image-name
        EOF
