name: Build and Run Docker Containers on VM

on:
  workflow_dispatch:
  
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Set up SSH key for authentication
    - name: Set up SSH key for VM
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.VM_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Optionally, add the VM's public key to known hosts to prevent verification prompt
        ssh-keyscan -H 34.132.171.168 >> ~/.ssh/known_hosts

        # Step 3: SSH into VM and run Docker build and container commands
        ssh -T -o StrictHostKeyChecking=no ubuntu@34.132.171.168 << 'EOF'
          # Navigate to the directory where your Dockerfiles are located
          cd /home/kiritisagar

          # Build Docker image
          docker build -t your-image-name .

          # Run the Docker container
          docker run -d -p 80:80 your-image-name
        EOF
