name: Build and Deploy Docker on VM

on:
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        # Use GitHub Secret to securely provide the SSH private key
        echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        # Optionally, add the VM's public key to known hosts to prevent verification prompt
        ssh-keyscan -H 34.132.171.168 >> ~/.ssh/known_hosts

    - name: Deploy Docker container on VM
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: 34.132.171.168
        username: ubuntu
        key: ${{ secrets.GCP_SSH_KEY }}  # Use the SSH private key stored as a GitHub secret
        port: 22
        script: |
          
          # Run the new Docker container
          cd /home/kiritisagar
          docker build -t your-image-name . 
          docker run -d -p 80:80 your-image-name
