name: Docker Build & Run on GCP VM

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  docker-build-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 1: Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: keen-metric-442709-h0
          version: latest
          skip_install: false

      # Step 2: Authenticate with Google Cloud
      - name: Authenticate with Google Cloud
        run: |
          echo "${{ secrets.GCP_KEY_JSON }}" > $HOME/gcp-key.json
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY_JSON }}

      # Step 3: SSH into the VM to build and run Docker containers
      - name: SSH into VM and Build & Run Docker
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.GCP_SSH_KEY }}" > ~/.ssh/google_compute_engine
          chmod 600 ~/.ssh/google_compute_engine
          echo "SSH key and permissions set."

          # Run Docker build and container command using SSH
          gcloud compute ssh spot --zone us-central1-a --tunnel-through-iap --command "
            docker build -t my-app /home/kiritisagar &&
            docker run -d --name my-app-container -p 80:80 my-app
          "
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY_JSON }}
