name: GCP VM STOP

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  authenticate-gcp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 1: Set up Google Cloud CLI
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: keen-metric-442709-h0
          version: latest
          skip_install: false

      # Step 2: Check if the GCP_KEY_JSON secret is available
      - name: Check GCP_KEY_JSON secret length
        run: |
          echo "Secret length: ${#GCP_KEY_JSON}"
          if [ -z "${GCP_KEY_JSON}" ]; then
            echo "Error: GCP_KEY_JSON secret is not found or is empty" && exit 1
          fi
        env:
          GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}

      # Step 3: Write the GCP_KEY_JSON to a file
      - name: Save GCP service account key to file
        run: |
          echo "$GCP_KEY_JSON" > $HOME/gcp-key.json
        env:
          GCP_KEY_JSON: ${{ secrets.GCP_KEY_JSON }}

      # Step 4: Validate the GCP service account key (check if JSON is valid)
      - name: Validate GCP Key JSON
        run: |
          if jq empty $HOME/gcp-key.json; then
            echo "Valid JSON file"
          else
            echo "Error: The JSON file is invalid" && exit 1
          fi

      # Step 5: Authenticate with Google Cloud using the service account key
      - name: Authenticate with Google Cloud
        run: |
          gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
          gcloud config set project keen-metric-442709-h0

      # Step 6: Stop the GCP VM instance
      - name: Stop GCP VM Instance
        run: |
          gcloud compute instances stop spot --zone us-central1-a
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_KEY_JSON }}
