name: GCP Deployment

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: keen-metric-442709-h0
        credentials: ${{ secrets.GCP_KEY_JSON }}  # This uses the GitHub secret directly

    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_KEY_JSON }}" > $HOME/gcp-key.json
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json

    - name: Deploy to Google Cloud
      run: |
        # Replace with your specific deployment commands
        gcloud deploy --project keen-metric-442709-h0
