name: GCP Deployment

on:
  workflow_dispatch:  # This allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: keen-metric-442709-h0
        credentials: ${{ secrets.GCP_KEY_JSON }}  # This uses the GitHub secret directly

    - name: Debugging the GCP_KEY_JSON secret
      run: |
        echo "Secret length: ${#GCP_KEY_JSON}"  # Check the length of the secret
        if [ -z "${{ secrets.GCP_KEY_JSON }}" ]; then
          echo "Error: GCP_KEY_JSON secret is not found or is empty" && exit 1
        fi

    - name: Write GCP key JSON to a file and validate
      run: |
        # Step 1: Check if the secret is valid JSON by writing it to a file
        echo "${{ secrets.GCP_KEY_JSON }}" > $HOME/gcp-key.json

        # Step 2: Validate if the JSON is correctly formatted
        if jq empty $HOME/gcp-key.json; then
          echo "Valid JSON file"
        else
          echo "Error: The JSON file is invalid" && exit 1
        fi

        # Step 3: Authenticate with Google Cloud using the service account key file
        gcloud auth activate-service-account --key-file=$HOME/gcp-key.json
        gcloud config set project keen-metric-442709-h0

    - name: Deploy to Google Cloud
      run: |
        # Your deploy commands here, for example:
        # gcloud app browse
        gcloud deploy --project keen-metric-442709-h0
