name: Stop GCP VM

on:
  workflow_dispatch:

jobs:
  stop-vm:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v1
      with:
        service_account_key: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}
        export_default_credentials: true

    - name: Authenticate with Google Cloud
      run: |
        echo "${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}" | gcloud auth activate-service-account --key-file=-
        gcloud auth list
        gcloud config list
        gcloud projects list

    - name: Stop GCP VM
      run: |
        gcloud compute instances stop "spot" \
          --project="keen-metric-442709-h0" \
          --zone="us-central1-a"
